export const salle1 = [
    ['red','red','red','red','red','red','red','red','red','red','blue','red','red','red','red','red','red','red','red','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','blue','red','red','red','red','red','red','red','red','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red'],
];

export const salle2 = [
    ['red','red','red','red','red','red','red','red','red','red','blue','blue','red','red','red','red','red','red','red','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','blue','blue','red','red','red','red','red','red','red','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','green','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red'],
    ['red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red','red'],
];